### PR TITLE
#156687695 Add New Dashboard Tab for Unresolved Checks

### PR DESCRIPTION
**Pull request by ghost**
#### What does this PR do?
Adds a new dashboard link that allows a user to view failing jobs that they have been notified about.

The following files have changed:
* `hc/front/views.py`
* `hc/front/urls.py`
* `templates/base.html`

And the following files have been created:
* `templates/front/my_unresolved_checks.html`
* `hc/front/tests/test_adds_unresolved_checks.py`

#### Description of Task to be completed?
When a user logs in, the dashboard tab "CHECKS" that displays the user's past checks does not have failing jobs in a separate view from the rest of the past checks. Create a new dashboard tab to show only the checks that have failed and that the user has been notified about.
#### How should this be manually tested?
Run the app as described in the README. Create an account, and login. Check whether the dashboard contains a tab for unresolved checks dubbed "**UNRESOLVED CHECKS**".

Create a Check, make it fail and stay failed past the grace period. Check the notification on your email for this check. Check whether the Check appears under "**UNRESOLVED CHECKS**" tab on the dashboard.
#### What are the relevant pivotal tracker stories?
* https://www.pivotaltracker.com/n/projects/2163622
* Story ID: 156687695
#### Screenshots?
The screenshot below is showing an unresolved check:

unresolved_checks_1

The screenshot below is showing a message when there is no unresolved checks:

unresolved_checks_2

### CODE REVIEW

**Review by zenjutahi — APPROVED** [review]

**Review by Collins33 — APPROVED** [review]

**Comment by Collins33** [comment]
I like how the UI for the unresolved stuff looks. There is a nice blend of colors that does not throw the user off

**Review by jimmykamau — CHANGES_REQUESTED** [review]
Kindly add tests for the `my_unresolved_checks` function

**Comment by ghost** [comment]
I added the tests. I added them in this module: `hc/front/tests/test_adds_unresolved_checks.py`. Let me know if you feel some edge case I forgot to cover

**Review by zenjutahi — APPROVED** [review]
I see that you have covered the test cases for the functionalities you added to the project. Good work.

**Review by jimmykamau — APPROVED** [review]

**Pull request merged**
