### PR TITLE
#156687701 User should have a Help Center 

### PR DESCRIPTION
**Pull request by Collins33**
### WHAT DOES THE PR DO
It adds a help-desk sections with FAQs and help videos

### TESTING IT
Click the help-desk part of the navigation bar

### SCREENSHOTS
screen shot 2018-05-04 at 10 32 19
screen shot 2018-05-07 at 11 58 37

### PIVOTAL TRACKER ID
#156687701

### CODE REVIEW

**Review by zenjutahi — DISMISSED** [review]

**Review by Bonifase — COMMENTED** [review]
I like the good job, I hope you will work on the FQAs content alignment as proposed by the PO

**Comment by ghost** [comment]
I like your UI, you can improve it by increasing the margin between them and also aligning them as proposed by the PO. Good job, keep up

**Comment by alexmochu** [comment]
@Collins33 I think if you added a link to the FAQ/Help Center section on your PR, it would make it easier for anyone reviewing your PR/work. The screenshots are good but a live link to your work would be better.

**Comment by Collins33** [comment]
@alexmochu Thank you for the feedback. I will include the link once the changes get merged to develop

**Comment by Collins33** [comment]
@murageden Thank you for the feedback. I have implemented the changes from the PO. You can look at the pr screenshots

**Comment by zenjutahi** [comment]
@Collins33 With the changes you currently have resulting from the feedback given I believe your work on the UI covers the tasks given.

**Comment by Collins33** [comment]
@zenjutahi Thank you for your feedback. I have implemented the changes. If you notice anything that I can change, reach out to me.

**Review by jimmykamau — CHANGES_REQUESTED** [review]
You shouldn't be creating a PR to `master`

**Comment by Collins33** [comment]
@jimmykamau I have created a new pull request to master and invited you to review

**Pull request closed without merging**
